-- quién es el alumno con el mejor puntaje
SELECT TOP 1
       E.NOM_Y_APE,
       AVG(N.NOTA) as PROMEDIO
  FROM NOTA N
 INNER JOIN CURSA C ON N.ID_CURSA = C.ID_CURSA
 INNER JOIN ESTUDIANTE E ON C.NRO_LEGAJO = E.NRO_LEGAJO
 GROUP BY E.NOM_Y_APE
 ORDER BY PROMEDIO DESC;