-- 2.11: ¿Cuál es el promedio de edad por país?
SELECT P.NOM_PAIS,
       COUNT(CUIL) CANTIDAD_DOCENTES,
       AVG(DATEDIFF(YEAR, D.FECHA_NAC, GETDATE())) EDAD_PROMEDIO
  FROM DOCENTE D
 INNER JOIN PAIS P ON D.ID_PAIS_NAC = P.ID_PAIS
 GROUP BY P.NOM_PAIS
 ORDER BY EDAD_PROMEDIO;