-- 2.13: ¿De qué cursos participan?
SELECT NOM_DOCENTE, C.NOMBRE_CURSO
  FROM DOCENTE DC
 INNER JOIN DICTA D ON DC.CUIL = D.CUIL
 INNER JOIN CURSO C ON D.ID_CURSO = C.ID_CURSO
 GROUP BY NOM_DOCENTE, C.NOMBRE_CURSO;
