-- 2.14: ¿Cuál es el puntaje promedio de los alumnos de cada uno?
SELECT NOM_DOCENTE, AVG(N.NOTA) AS PROMEDIO_PUNTAJE
  FROM DOCENTE DC
 INNER JOIN DICTA D ON DC.CUIL = D.CUIL
 INNER JOIN CURSO C ON D.ID_CURSO = C.ID_CURSO
 INNER JOIN CURSA CU ON C.ID_CURSO = CU.ID_CURSO
 INNER JOIN NOTA N ON CU.ID_CURSA = N.ID_CURSA
 GROUP BY NOM_DOCENTE;
