-- 2.15: ¿Cuál es el puntaje promedio de los alumnos por materia y por profesor?
SELECT NOM_DOCENTE, MA.NOMBRE_MATERIA, AVG(N.NOTA) AS PROMEDIO_PUNTAJE
  FROM DOCENTE DC
 INNER JOIN DICTA D ON DC.CUIL = D.CUIL
 INNER JOIN CURSO C ON D.ID_CURSO = C.ID_CURSO
 INNER JOIN CURSA CU ON C.ID_CURSO = CU.ID_CURSO
 INNER JOIN NOTA N ON CU.ID_CURSA = N.ID_CURSA
 INNER JOIN MATERIA MA ON D.CODIGO_MATERIA = MA.CODIGO_MATERIA
 GROUP BY NOM_DOCENTE, MA.NOMBRE_MATERIA;
