-- 3.0: ¿Cuál es el contenido de cada curso?
SELECT NOMBRE_CURSO, NOMBRE_MATERIA
  FROM CURSO
 INNER JOIN DICTA D ON CURSO.ID_CURSO = D.ID_CURSO
 INNER JOIN MATERIA M ON D.CODIGO_MATERIA = M.CODIGO_MATERIA
 GROUP BY NOMBRE_CURSO, NOMBRE_MATERIA;