-- 3.1: ¿Cómo está organizado el dictado de las materias?
SELECT NOMBRE_CURSO, TURNO, NOMBRE_MATERIA, DI.NOMRE_DIA, HORA_DESDE, HORA_HASTA
  FROM DICTA
  INNER JOIN CURSO C ON DICTA.ID_CURSO = C.ID_CURSO
  INNER JOIN MATERIA M ON DICTA.CODIGO_MATERIA = M.CODIGO_MATERIA
  INNER JOIN DOCENTE D ON DICTA.CUIL = D.CUIL
  INNER JOIN DIA DI ON DICTA.ID_DIA = DI.ID_DIA;