-- 3.2: ¿Qué alumnos participan de cada curso?
SELECT NOM_Y_APE, NOMBRE_CURSO
  FROM ESTUDIANTE
 INNER JOIN CURSA C ON ESTUDIANTE.NRO_LEGAJO = C.NRO_LEGAJO
 INNER JOIN CURSO CO ON C.ID_CURSO = CO.ID_CURSO;