-- 3.3: ¿Qué profesores dictan las materias de cada curso?
SELECT NOMBRE_CURSO, NOMBRE_MATERIA, TURNO, NOM_DOCENTE
  FROM DOCENTE
 INNER JOIN DICTA D ON DOCENTE.CUIL = D.CUIL
 INNER JOIN CURSO C ON D.ID_CURSO = C.ID_CURSO
 INNER JOIN MATERIA M ON D.CODIGO_MATERIA = M.CODIGO_MATERIA;