-- 4.0: ¿Cuál es el ingreso mensual de la institución por curso?
SELECT C.NOMBRE_CURSO, C.TURNO, COUNT(ID_CURSA) AS CANTIDAD_ALUMNOS, SUM(CUOTA_ALUMNO) AS INGRESOS_X_CURSO
  FROM (
    SELECT C.NOMBRE_CURSO, C.TURNO, ID_CURSA, CUOTA_ALUMNO
      FROM CURSA
     INNER JOIN CURSO C ON CURSA.ID_CURSO = C.ID_CURSO
) C
 GROUP BY C.NOMBRE_CURSO, C.TURNO;



